const data = [
  {
    _id: 1,
    bgImg: "../../src/assets/images/01.jpg",
    title: "LOREM IPSUM DOLOAR SIT AMET",
    subtitle: "Lorem ipsum doloar soapet, seit jahr",
    category: "Spring",
    promotion: "HOT",
    gender: "Women",
    price: "100.36",
    discount: "0.5",
    description:
      "LOREM ipsum doloar sit amet, consectetur adipiscing elit. Morbi commodo felis",
    active: false,
  },
  {
    _id: 2,
    bgImg: "../../src/assets/images/02.jpg",
    title: "LOREM IPSUM DOLOAR SIT AMET",
    subtitle: "Lorem ipsum doloar soapet, seit jahr",
    category: "Spring",
    promotion: "HOT",
    gender: "Women",
    price: "120.76",
    discount: "0.2",
    description:
      "LOREM ipsum doloar sit amet, consectetur adipiscing elit. Morbi commodo felis",
    active: false,
  },
  {
    _id: 3,
    bgImg: "../../src/assets/images/03.jpg",
    title: "LOREM IPSUM DOLOAR SIT AMET",
    subtitle: "Lorem ipsum doloar soapet, seit jahr",
    category: "Spring",
    promotion: "HOT",
    gender: "Women",
    price: "180.98",
    discount: "0",
    description:
      "LOREM ipsum doloar sit amet, consectetur adipiscing elit. Morbi commodo felis",
    active: false,
  },
  {
    _id: 4,
    bgImg: "../../src/assets/images/04.jpg",
    title: "LOREM IPSUM DOLOAR SIT AMET",
    subtitle: "Lorem ipsum doloar soapet, seit jahr",
    category: "Spring",
    promotion: "HOT",
    gender: "Women",
    price: "100.36",
    discount: "0.5",
    description:
      "LOREM ipsum doloar sit amet, consectetur adipiscing elit. Morbi commodo felis",
    active: false,
  },
  {
    _id: 5,
    bgImg: "../../src/assets/images/05.jpg",
    title: "LOREM IPSUM DOLOAR SIT AMET",
    subtitle: "Lorem ipsum doloar soapet, seit jahr",
    category: "Spring",
    promotion: "HOT",
    gender: "Women",
    price: "100.36",
    discount: "0.5",
    description:
      "LOREM ipsum doloar sit amet, consectetur adipiscing elit. Morbi commodo felis",
    active: false,
  },
  {
    _id: 6,
    bgImg: "../../src/assets/images/06.jpg",
    title: "LOREM IPSUM DOLOAR SIT AMET",
    subtitle: "Lorem ipsum doloar soapet, seit jahr",
    category: "Spring",
    promotion: "HOT",
    gender: "Women",
    price: "100.36",
    discount: "0.5",
    description:
      "LOREM ipsum doloar sit amet, consectetur adipiscing elit. Morbi commodo felis",
    active: false,
  },
  {
    _id: 7,
    bgImg: "../../src/assets/images/07.jpg",
    title: "LOREM IPSUM DOLOAR SIT AMET",
    subtitle: "Lorem ipsum doloar soapet, seit jahr",
    category: "Spring",
    promotion: "HOT",
    gender: "Women",
    price: "100.36",
    discount: "0.5",
    description:
      "LOREM ipsum doloar sit amet, consectetur adipiscing elit. Morbi commodo felis",
    active: true,
  },
  {
    _id: 8,
    bgImg: "../../src/assets/images/08.jpg",
    title: "LOREM IPSUM DOLOAR SIT AMET",
    subtitle: "Lorem ipsum doloar soapet, seit jahr",
    category: "Spring",
    promotion: "HOT",
    gender: "Women",
    price: "100.36",
    discount: "0.5",
    description:
      "LOREM ipsum doloar sit amet, consectetur adipiscing elit. Morbi commodo felis",
    active: false,
  },
];

export default data;
